#!/usr/bin/env python3

import subprocess
import sys, os

def display_credits():
    print("*" * 50)
    print("*")
    print(f"*    j_presto (Version 1.1.1)")
    print("*")
    print(f"*        Author : Jinzen Ikebe")
    print(f"* First Release : 2024-11-11")
    print(f"*  Current ver. : 2025-07-10")
    print("*")
    print(f"*" * 50)
    print()
    license_path = os.path.join(os.environ.get("J_PRESTO_PATH"), "LICENSE.md")
    try:
        with open(license_path, "r", encoding="utf-8") as file:
            license_content = file.read()
            print(license_content)
    except FileNotFoundError:
        print("Error: License file not found.") ; sys.exit(1)

def run_program(program_name, args):
    program_dict = {"md_run", "GEprep", "Ens_Ana", "PCAaxis", "PCAproj", "distrib", "pdb_alignfit", "nt_gen", "nt_conv", "conmut", "pick_conf", "ttp_se", "genlist", "MSPER", "initpep", "gen_db", "prep", "batch_set", "pdb_movie", "get_tmpl", "manual"}
    program_dict_nohelp = {"md_run", "GEprep", "Ens_Ana"}
    try:
        sys.stdout.flush()
        program_path = os.path.join(os.environ.get("J_PRESTO_PATH"), "sp", program_name)
        if program_name in program_dict:
            if len(args) > 1:
                if program_name in program_dict_nohelp:
                    if args[1] == "-h":
                        print(f"To check how to use '{program_name}', please execute 'j_presto manual'.") ; sys.exit(0)
                    elif os.path.isfile(args[1]):
                        with open(args[1], 'r') as input_file:
                            subprocess.run([program_path], stdin=input_file, check=True)
                else:
                    subprocess.run([program_path] + args, check=True)
        else:
            subprocess.run([program_path] + args, check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error occurred while running {program_name}: {e}") ; sys.exit(1)

def main():
    if len(sys.argv) < 2:
        print("Usage: j_presto <program_name> <arguments>")
        sys.exit(1)

    if sys.argv[1] == "-h":
        print("Usage: j_presto <function> <arguments>\n")
        print("functions:")
        print("")
        print("initpep         : Preperation of extended initial structures for folding simulation.")
        print("pdb_alignfit    : Superimposition of query structure to target one based on sequence alignment.")
        print("nt_gen          : Generation of atomic name correspondence table from a PREP and a PDB file.")
        print("nt_conv         : Convert residue and atom names in a PREP and a PDB file based on a name table.")
        print("gen_db          : Generation of a database file (*.tpldb) for creating j_presto topology files (*.tpl).")
        print("prep            : Preparation of input files (*.pdb, *.tpl, and *.shk files) for MD simulations.")
        print("md_run          : Execution of MD simulation or energy minimization calculation.")
        print("batch_set       : Setting up all the necessary files and directories required to run multiple MD simulations efficiently.")
        print("GEprep          : Preparation of a parameter file (*.nf) for Generalized Ensemble MD simulations such as McMD and ALSD.")
        print("Ens_Ana         : Performing analysis of conformational ensembles obtained from simulation results.")
        print("PCAaxis         : Calculating axes for principal component analysis (PCA) through diagonalization.")
        print("PCAproj         : Projecting each structure onto PCA subspace.")
        print("distrib         : Generation of statistical distribution data from weighted input values for one- or two-dimensional variables.")
        print("pick_conf       : Extraction and ranking structures based on user-defined conditions and event timings.")
        print("ttp_se          : Calculation of weighted averages and standard errors of the data.")
        print("pdb_movie       : Generation of a multi-model PDB file from sequential single-structure PDB files for trajectory visualization.")
        print("MSPER           : Predict mutation sites to improve enzyme selectivity.")
        print("conmut          : Propose mutations to improve enzyme stability from input amino acid sequences using the consensus method.")
        print("get_tmpl        : Obtaining templates of input files and scripts for excuting j_presto.")
        print("genlist         : Generate file path lists and data ranges for MD and analysis inputs.")
        print("manual          : Viewing the manual.")
        print("\n")
        sys.exit(1)

    program_name = sys.argv[1]
    args = ["j_presto"] + sys.argv[2:]

    display_credits()
    if program_name == "manual":
        args = [args[0], os.path.join(os.environ.get("J_PRESTO_PATH"), "manual.txt")] + sys.argv[2:]
    run_program(program_name, args)

if __name__ == "__main__":
    main()

