#!/usr/bin/env python3

import argparse, os, sys, time

def display_credits():
    print("*" * 50)
    print("*")
    print(f"*    test (Version 1.0.0)")
    print("*")
    print(f"*        Author : Jinzen Ikebe")
    print(f"* First Release : 2025-01-01")
    print(f"*  Current ver. : 2025-01-01")
    print("*")
    print(f"*" * 50)
    print()
    license_path = os.path.join(os.environ.get("J_PRESTO_PATH"), "LICENSE.md")
    try:
        with open(license_path, "r", encoding="utf-8") as file:
            license_content = file.read()
    except FileNotFoundError:
        print("Error: License file not found.") ; sys.exit(1)

def main():
    stime = time.perf_counter()
    parser = argparse.ArgumentParser(description="test")
    parser.add_argument('access_key', help=argparse.SUPPRESS)
    parser.add_argument("input", help="Input data")
    parser.add_argument("-o", "--output", type=str, default="output.txt", help="Output file name (default: output.txt)")

    args = parser.parse_args()
    if args.access_key != "j_presto":
        sys.exit(1)
    display_credits()




    etime = time.perf_counter()
    print(f"\nExecution time : {etime - stime} (S)")
    print(f"\n+++ Program j_presto test normally ended +++")

if __name__ == "__main__":
    main()

